name: Deploy to Github Pages

on:
  push:
    branches: ["Gen2"]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages


# Allow one concurrent deployment
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

# Default to bash
defaults:
  run:
    shell: bash
    working-directory: .

jobs:
  generateClientCode:
    uses: ./.github/workflows/build-client.yml
  deployToPages:
    name: Deploy to Github Pages
    needs: generateClientCode
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download client code generated
        uses: actions/download-artifact@v4
        with:
          name: client-dist
          path: ./client-dist
      - name: Upload as pages artifact 
        uses: actions/upload-artifact@v3
        with:
          path: ./client-dist
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1