name: Deploy to Github Pages

on:
  push:
    branches: ["Gen2"]

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Default to bash
defaults:
  run:
    shell: bash
    working-directory: .

jobs:
  generateClientCode:
    uses: ./.github/workflows/build-client.yml
  uploadToPages:
    name: Deploy to Github Pages
    needs: generateClientCode
    runs-on: ubuntu-latest
    steps:
      - name: Download client code generated
        uses: actions/download-artifact@v4
        with:
          name: client-dist
          path: ./client-dist
      - name: Upload as pages artifact 
        uses: actions/upload-artifact@v3
        with:
          path: ./client-dist
  deployToPages:
    runs-on: ubuntu-latest
    needs: uploadToPages
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.uploadToPages.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
